version: '3.8'

networks:
  monitoring-network:
    external: true

services:
  go-log-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-log-generator
    working_dir: /app
    command:
      - ./go_generator
      - -mode=${GENERATOR_MODE}
      - -url=${GENERATOR_URL}
      - -rps=${GENERATOR_RPS}
      - -duration=${GENERATOR_DURATION}
      - -bulk-size=${GENERATOR_BULK_SIZE}
      - -worker-count=${GENERATOR_WORKERS}
      - -connection-count=${GENERATOR_CONNECTIONS}
      - -max-retries=${GENERATOR_MAX_RETRIES}
      - -retry-delay=${GENERATOR_RETRY_DELAY}
      - -enable-metrics=${GENERATOR_METRICS_ENABLED}
      - -verbose=${GENERATOR_VERBOSE}
      - -web-access-weight=${GENERATOR_LOG_DISTRIBUTION_WEB_ACCESS}
      - -web-error-weight=${GENERATOR_LOG_DISTRIBUTION_WEB_ERROR}
      - -application-weight=${GENERATOR_LOG_DISTRIBUTION_APPLICATION}
      - -metric-weight=${GENERATOR_LOG_DISTRIBUTION_METRIC}
      - -event-weight=${GENERATOR_LOG_DISTRIBUTION_EVENT}
    ports:
      - "${GENERATOR_METRICS_PORT}:9090"
    networks:
      - monitoring-network
    env_file:
      - .env
    restart: "no"
