auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
  wal:
    enabled: true
    dir: /loki/wal

distributor:
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: "2023-01-01"
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor
  compaction_interval: 5m
  retention_enabled: false
  ring:
    kvstore:
      store: inmemory

limits_config:
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  max_entries_limit_per_query: 1000000
  allow_structured_metadata: ${STRUCTURED_METADATA}

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules
  ring:
    kvstore:
      store: inmemory
  enable_api: true

querier:
  max_concurrent: 16
