metrics: true

generator:
  maxPerf:
    steps: 3
    stepDuration: 10
    impact: 2
    baseRPS: 10
    startPercent: 10
    incrementPercent: 10

  stability:
    stepDuration: 60
    impact: 5
    baseRPS: 10
    stepPercent: 100

  bulkSize: 10
  maxRetries: 3
  retryDelayMs: 500
  timeoutMs: 5000

  verbose: false

  distribution:
    web_access: 60
    web_error: 10
    application: 20
    event: 5
    metric: 5

querier:
  maxPerf:
    steps: 3
    stepDuration: 10
    impact: 2
    baseRPS: 10
    startPercent: 10
    incrementPercent: 10

  stability:
    stepDuration: 60
    impact: 5
    baseRPS: 10
    stepPercent: 100

  maxRetries: 3
  retryDelayMs: 500
  timeoutMs: 30000

  verbose: false

  distribution:
    simple: 20
    complex: 20
    analytical: 15
    timeseries: 15
    stat: 15
    topk: 15

  times:
    last5m: 10
    last15m: 10
    last30m: 10
    last1h: 10
    last2h: 10
    last4h: 10
    last8h: 10
    last12h: 5
    last24h: 2.5
    last48h: 1.5
    last72h: 1
    custom:
      percents_offset_left_border:
        15m: 10
        30m: 10
        1h: 10
        2h: 10
        4h: 10
        8h: 10
        12h: 5
        24h: 2.5
        48h: 1.5
      percents_offset_right_border:
        1h: 50
        2h: 30
        4h: 10
        8h: 10