mode: generator
system: victoria
durationSeconds: 60

generator:
  urlLoki: http://loki:3100
  urlES: http://victoria-logs:9428
  urlVictoria: http://elasticsearch:9200

  rps: 2
  bulkSize: 10
  maxRetries: 3
  retryDelayMs: 500

  workerCount: 4
  connectionCount: 10
  verbose: false

  distribution:
    web_access: 60
    web_error: 10
    application: 20
    event: 5
    metric: 5

querier:
  urlLoki: http://loki:3100
  urlES: http://victoria-logs:9428
  urlVictoria: http://elasticsearch:9200

  rps: 10
  maxRetries: 3
  retryDelayMs: 500

  workerCount: 2
  verbose: false

  distribution:
    exact_match: 30
    time_range: 40
    label_filter: 20
    complex_query: 10

metrics:
  enabled: true
  port: 9090
