durationSeconds: 10
metrics: true

generator:
  rps: 2
  bulkSize: 10
  maxRetries: 3
  retryDelayMs: 500

  workerCount: 4
  connectionCount: 10
  verbose: true

  distribution:
    web_access: 60
    web_error: 10
    application: 20
    event: 5
    metric: 5

querier:
  rps: 10
  maxRetries: 3
  retryDelayMs: 500

  workerCount: 2
  verbose: true

  distribution:
    simple: 20
    complex: 20
    analytical: 15
    timeseries: 15
    stat: 15
    topk: 15
