durationSeconds: 10
metrics: true

generator:
  rps: 2
  bulkSize: 10
  maxRetries: 3
  retryDelayMs: 500

  workerCount: 4
  connectionCount: 10
  verbose: true

  distribution:
    web_access: 60
    web_error: 10
    application: 20
    event: 5
    metric: 5

querier:
  rps: 10
  maxRetries: 3
  retryDelayMs: 500

  workerCount: 2
  verbose: true

  distribution:
    exact_match: 30
    time_range: 40
    label_filter: 20
    complex_query: 10
