metrics: true

generator:
  maxPerf:
    steps: 3
    stepDuration: 10
    impact: 2
    baseRPS: 10
    startPercent: 10
    incrementPercent: 10

  stability:
    stepDuration: 60
    impact: 5
    baseRPS: 10
    stepPercent: 100

  bulkSize: 10
  maxRetries: 3
  retryDelayMs: 500
  timeoutMs: 5000

  verbose: false

  distribution:
    web_access: 60
    web_error: 10
    application: 20
    event: 5
    metric: 5

querier:
  maxPerf:
    steps: 3
    stepDuration: 10
    impact: 2
    baseRPS: 10
    startPercent: 10
    incrementPercent: 10

  stability:
    stepDuration: 60
    impact: 5
    baseRPS: 10
    stepPercent: 100

  maxRetries: 3
  retryDelayMs: 500
  timeoutMs: 30000

  verbose: false

  distribution:
    simple: 20
    complex: 20
    analytical: 15
    timeseries: 15
    stat: 15
    topk: 15
