version: '3.8'

networks:
  monitoring-network:
    external: true

services:
  go-log-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-log-generator
    working_dir: /app
    command:
      - "./load_tool"
      - "-config=/app/config.yaml"
      - "-hosts=/app/db_hosts.yaml"
      - "-system=${SYSTEM}"
      - "-mode=${MODE}"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./db_hosts_docker.yaml:/app/db_hosts.yaml
      - ./logs:/app/logs
    ports:
      - "${LOAD_METRICS_PORT:-9090}:9090"
    networks:
      - monitoring-network
    restart: "no"
