global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'victoria-metrics'
    static_configs:
      - targets: ['victoria-metrics:8428']
        labels:
          instance: 'victoria-metrics'

  - job_name: 'log-generators'
    static_configs:
      - targets: ['go-log-generator:9090']
        labels:
          instance: 'go-log-generator'
          service: 'log-generator'
          environment: 'development'

  - job_name: 'victorialogs'
    static_configs:
      - targets: ['victorialogs:9428']
        labels:
          instance: 'victorialogs'
          service: 'log-storage'
          environment: 'development'

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
        labels:
          instance: 'loki'
          service: 'log-storage'
          environment: 'development'
    metrics_path: '/metrics'

  - job_name: 'elasticsearch-exporter'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
        labels:
          instance: 'elasticsearch'
          service: 'log-storage'
          environment: 'development'
