{
 "title": "Loki Metrics",
 "tags": [ "loki" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "jobs",
    "label": "Job",
    "query": {
     "query": "label_values(loki_build_info,job)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Loki General Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "loki_build_info" }
     ]
    },
    {
     "title": "Features Currently Set",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "deprecated_flags_inuse_total{job=\"$jobs\"}",
       "legendFormat": "Deprecated"
      },
      {
       "expr": "loki_experimental_features_in_use_total{job=\"$jobs\"}",
       "legendFormat": "Experimental"
      }
     ]
    },
    {
     "title": "Panics",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "loki_panic_total{job=\"$jobs\"}",
       "legendFormat": "The total number of panics triggered"
      }
     ]
    },
    {
     "title": "Replication Factor",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "loki_distributor_replication_factor{job=\"$jobs\"}",
       "legendFormat": "The configured replication factor"
      }
     ]
    },
    {
     "title": "Internal Log Messages",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(loki_internal_log_messages_total{job=\"$jobs\"})"
      }
     ]
    },
    {
     "title": "Message Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "sum(loki_log_messages_total)" }
     ]
    },
    {
     "title": "Total Goroutines",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(go_goroutines)",
       "legendFormat": "Number of goroutines that currently exist"
      }
     ]
    },
    {
     "title": "Total Threads",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(go_threads{job=\"$jobs\"})",
       "legendFormat": "Number of OS threads created"
      }
     ]
    },
    {
     "title": "Loki Version",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "loki_build_info", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Distributor Volume",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_bytes_received_total{job=\"$jobs\"}[$__rate_interval])) by(tenant)",
       "legendFormat": "{{ tenant }}"
      }
     ]
    },
    {
     "title": "Ingester Chunk Operations",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rate(loki_ingester_chunks_created_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Create"
      },
      {
       "expr": "sum(rate(loki_ingester_chunks_stored_total{job=\"$jobs\"}[$__rate_interval])) by (tenant) ",
       "legendFormat": "Store / {{ tenant }}"
      }
     ]
    },
    {
     "title": "Ingester Chunks Volume",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_chunk_stored_bytes_total{job=\"$jobs\"}[$__rate_interval])) by (tenant)",
       "legendFormat": "{{ tenant }}"
      }
     ]
    },
    {
     "title": "Go Version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "go_info{job=\"$jobs\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Store Operations Stored",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(loki_chunk_store_stored_chunks_total{job=\"$jobs\"}[$__rate_interval])) by (user)",
       "legendFormat": "{{ user}}"
      }
     ]
    },
    {
     "title": "Ingester Stream Operations",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_streams_created_total{job=\"$jobs\"}[$__rate_interval])) by (tenant)",
       "legendFormat": "Create / {{ tenant }}"
      },
      {
       "expr": "sum(rate(loki_ingester_streams_removed_total{job=\"$jobs\"}[$__rate_interval])) by (tenant)",
       "legendFormat": "Delete / {{ tenant }}"
      }
     ]
    },
    {
     "title": "Distributor Lines",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_lines_received_total{job=\"$jobs\"}[$__rate_interval])) by(tenant)",
       "legendFormat": "{{ tenant }}"
      }
     ]
    },
    {
     "title": "Store Volume Stored",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rate(loki_chunk_store_stored_chunk_bytes_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "{{ user}}"
      }
     ]
    },
    {
     "title": "Ingester Chunk Size",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "Chunk Size"
      }
     ]
    },
    {
     "title": "Ingester Streams in Memory",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(loki_ingester_memory_streams{job=\"$jobs\"}) by(tenant)",
       "legendFormat": "{{ tenant }}"
      }
     ]
    },
    {
     "title": "Ingester Chunk Compression",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "Compression Ratio"
      }
     ]
    },
    {
     "title": "Index Chunks Downloaded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(loki_index_chunk_refs_total{job=\"$jobs\"}) by(status)",
       "legendFormat": "{{ status }}"
      }
     ]
    },
    {
     "title": "Ingester Chunks In Memory",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "loki_ingester_memory_chunks{job=\"$jobs\"}",
       "legendFormat": "Chunks in memory"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki API / Connections Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Request Durations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket[$__rate_interval])) by (le,route))",
       "legendFormat": "{{ route }}"
      }
     ]
    },
    {
     "title": "Messages Input",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(loki_log_messages_total[$__rate_interval])) by (level)",
       "legendFormat": "{{ level }}"
      }
     ]
    },
    {
     "title": "LogQL  Processed bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_bytes_processed_per_seconds_bucket[$__rate_interval])) by (le,type))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "LogQL Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket[$__rate_interval])) by (le,type))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Loki API - Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket[$__rate_interval])) by (le,method,route,status_code))",
       "legendFormat": "{{ method }} / {{ route }} / {{ status_code }}"
      }
     ]
    },
    {
     "title": "Loki API - Request Current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_inflight_requests{job=\"$jobs\"}[$__rate_interval])) by (method, route)",
       "legendFormat": "{{ method }} / {{ route }}"
      }
     ]
    },
    {
     "title": "Loki API - Response Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_response_message_bytes_bucket{job=\"$jobs\"}[$__rate_interval])) by (le,method,route))",
       "legendFormat": "{{ method }} / {{ route }}"
      }
     ]
    },
    {
     "title": "Loki API - Request Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_request_message_bytes_bucket{job=\"$jobs\"}[$__rate_interval])) by (le,method,route))",
       "legendFormat": "{{ method }} / {{ route }}"
      }
     ]
    },
    {
     "title": "Loki - TCP Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "loki_tcp_connections{job=\"$jobs\"}",
       "legendFormat": "{{ protocol }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Strams Stats",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(loki_ingester_streams_created_total[5m])",
       "legendFormat": "create"
      },
      {
       "expr": "rate(loki_ingester_streams_removed_total[5m])",
       "legendFormat": "delete"
      }
     ]
    },
    {
     "title": "Chunk Status",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(loki_ingester_chunks_created_total[5m])",
       "legendFormat": "create"
      },
      {
       "expr": "sum by (reason) (rate(loki_ingester_chunks_flushed_total[5m]))",
       "legendFormat": "flush / {{ reason }}"
      },
      {
       "expr": "sum by (fake) (rate(loki_ingester_chunks_stored_total[5m]))",
       "legendFormat": "stored"
      },
      {}
     ]
    },
    {
     "title": "Chunk Age",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_age_seconds_bucket[5m])) by (le))",
       "legendFormat": "ages"
      }
     ]
    },
    {
     "title": "Chunk Encode Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_encode_time_seconds_bucket[5m])) by (le))",
       "legendFormat": "durations."
      }
     ]
    },
    {
     "title": "Lines / Chunk",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_entries_bucket[5m])) by (le))",
       "legendFormat": "lines"
      }
     ]
    },
    {
     "title": "Chunk Compression Ratios",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket[5m])) by (le))",
       "legendFormat": "ratio"
      }
     ]
    },
    {
     "title": "Blocks / Chunk",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_blocks_per_chunk_bucket[5m])) by (le))",
       "legendFormat": "blocks"
      }
     ]
    },
    {
     "title": "Chunk Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket[5m])) by (le))",
       "legendFormat": "chunk size"
      }
     ]
    },
    {
     "title": "Chunks in Streams",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (tenan) (loki_ingester_memory_streams)",
       "legendFormat": "streams"
      }
     ]
    },
    {
     "title": "Chunks in Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "loki_ingester_memory_chunks", "legendFormat": "chunks" }
     ]
    }
   ]
  },
  {
   "title": "Loki Cache Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki Cache - Hits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_cache_hits{job=\"$jobs\"}[$__rate_interval])) by(name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Loki Cache - Fetched Keys",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_cache_fetched_keys{job=\"$jobs\"}[$__rate_interval])) by(name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Loki Cache - Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_cache_request_duration_seconds_bucket{job=\"$jobs\"}[$__rate_interval])) by (le,name,method))",
       "legendFormat": "{{ name }} / {{ method }}"
      }
     ]
    },
    {
     "title": "Loki Cache - Value Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_cache_value_size_bytes_bucket{job=\"$jobs\"}[$__rate_interval])) by (le,name,method))",
       "legendFormat": "{{ name }} / {{ method }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki Distributor Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki Distributor - Received Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_bytes_received_total{job=\"$jobs\"}[$__rate_interval])) by(tenant)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Loki Distributor - Received Lines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_lines_received_total{job=\"$jobs\"}[$__rate_interval])) by(tenant)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Loki Distributor - Batch Appents Sent To Ingester",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_ingester_appends_total{job=\"$jobs\"}[$__rate_interval])) by(ingester)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki Index Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki Index - Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_index_request_duration_seconds_bucket{job=\"$jobs\"}[$__rate_interval])) by (le,component,operation,status_code))",
       "legendFormat": "{{ component }} / {{ operation }} / {{ status_code }}"
      }
     ]
    },
    {
     "title": "Loki Index - Chunks Downloaded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_index_chunk_refs_total{job=\"$jobs\"}[$__rate_interval])) by (status)",
       "legendFormat": "{{ status }}"
      }
     ]
    },
    {
     "title": "Loki KV - Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_kv_request_duration_seconds_bucket{job=\"$jobs\"}[$__rate_interval])) by (le,kv_name,operation,role,status_code,type))",
       "legendFormat": "{{ kv_name }} / {{ type }} / {{ operation }} / {{ status_code }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki Ingester Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki Ingester - Client Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_client_request_duration_seconds_bucket{job=\"$jobs\"}[$__rate_interval])) by (le,operation,status_code))",
       "legendFormat": "{{ operation }} / {{ status_code }}"
      }
     ]
    },
    {
     "title": "Loki Ingester - Chunk Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(loki_ingester_chunks_created_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Chunk creations "
      },
      {
       "expr": "sum(rate(loki_ingester_chunks_flushed_total{job=\"$jobs\"}[$__rate_interval])) by (reason)",
       "legendFormat": "Chunk flushes / {{ reason }}"
      },
      {
       "expr": "sum(rate(loki_ingester_chunks_stored_total{job=\"$jobs\"}[$__rate_interval])) by (tenant) ",
       "legendFormat": "Chunks stored / {{ tenant }}"
      }
     ]
    },
    {
     "title": "Loki Ingester - Checkpoints",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(loki_ingester_checkpoint_creations_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Checkpoint creations "
      },
      {
       "expr": "rate(loki_ingester_checkpoint_creations_failed_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Checkpoint creation failures"
      },
      {
       "expr": "rate(loki_ingester_checkpoint_deletions_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Checkpoint deletions"
      },
      {
       "expr": "rate(loki_ingester_checkpoint_deletions_failed_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
       "legendFormat": "Checkpoint deletion failures"
      }
     ]
    },
    {
     "title": "Loki Ingester - Checkpoints Volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(loki_ingester_checkpoint_logged_bytes_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Bytes written to disk for checkpointing"
      }
     ]
    },
    {
     "title": "Loki Ingester - Checkpoint Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "loki_ingester_checkpoint_duration_seconds{job=\"$jobs\",quantile=\"0.99\"}",
       "legendFormat": "Time taken to create a checkpoint (0.99 quantile)"
      },
      {
       "expr": "loki_ingester_checkpoint_duration_seconds{job=\"$jobs\",quantile=\"0.9\"}",
       "legendFormat": "Time taken to create a checkpoint (0.9 quantile)"
      },
      {
       "expr": "loki_ingester_checkpoint_duration_seconds{job=\"$jobs\",quantile=\"0.5\"}",
       "legendFormat": "Time taken to create a checkpoint (0.5 quantile)"
      }
     ]
    },
    {
     "title": "Loki Ingester - Blocks Per Chunk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_blocks_per_chunk_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "Blocks per Chunk"
      }
     ]
    },
    {
     "title": "Loki Ingester - Chunk Compression Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 182 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "Compression ratio of chunks (when stored)"
      }
     ]
    },
    {
     "title": "Loki Ingester - Chunks In Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 182 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "loki_ingester_memory_chunks{job=\"$jobs\"}",
       "legendFormat": "Chunks in memory"
      }
     ]
    },
    {
     "title": "Loki Ingester - Chunk Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 190 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "Distribution of stored chunk sizes (when stored)"
      }
     ]
    },
    {
     "title": "Loki Ingester - Chunk Age",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 190 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_age_seconds_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "Distribution of chunk ages (when stored)"
      }
     ]
    },
    {
     "title": "Loki Ingester - Chunk Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_utilization_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "Distribution of stored chunk utilization (when stored)"
      }
     ]
    },
    {
     "title": "Loki Ingester - Chunk Stored Volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_chunk_stored_bytes_total{job=\"$jobs\"}[$__rate_interval])) by (tenant)",
       "legendFormat": "Bytes stored in chunks / {{ tenant }}"
      }
     ]
    },
    {
     "title": "Loki Ingester - Samples Per Chunk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 206 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_samples_per_chunk_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "Samples per chunk"
      }
     ]
    },
    {
     "title": "Loki Ingester - Chunk Bounds (Hours)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 206 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_bounds_hours_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "Distribution of chunk end-start durations"
      }
     ]
    },
    {
     "title": "Loki Ingester - Chunk Encoding Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_encode_time_seconds_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "Distribution of chunk encode times"
      }
     ]
    },
    {
     "title": "Loki Ingester - Lines Per Chunk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_entries_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "Distribution of stored lines per chunk (when stored)"
      }
     ]
    },
    {
     "title": "Loki Ingester - Stream Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 222 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_streams_created_total{job=\"$jobs\"}[$__rate_interval])) by (tenant)",
       "legendFormat": "Stream creations / {{ tenant }}"
      },
      {
       "expr": "sum(rate(loki_ingester_streams_removed_total{job=\"$jobs\"}[$__rate_interval])) by (tenant)",
       "legendFormat": "Stream deletetions / {{ tenant }}"
      }
     ]
    },
    {
     "title": "Loki Ingester - Streams In Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 222 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(loki_ingester_memory_streams{job=\"$jobs\"}) by (tenant)",
       "legendFormat": "Streams in memory / {{ tenant }}"
      }
     ]
    },
    {
     "title": "Loki Ingester - WAL Records",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 230 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(loki_ingester_wal_records_logged_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "WAL records logged"
      },
      {
       "expr": "rate(loki_ingester_wal_duplicate_entries_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Discarded entries during WAL replay due to existing in checkpoints"
      },
      {
       "expr": "rate(loki_ingester_wal_disk_full_failures_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "WAL write failures due to full disk"
      },
      {
       "expr": "sum(rate(loki_ingester_wal_discarded_samples_total{job=\"$jobs\"}[$__rate_interval])) by (reason)",
       "legendFormat": "WAL segment entries discarded during replay / {{ reason }}"
      }
     ]
    },
    {
     "title": "Loki Ingester - WAL Volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 230 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "loki_ingester_wal_bytes_in_use{job=\"$jobs\"}",
       "legendFormat": "Currently in use by the WAL recovery process"
      },
      {
       "expr": "rate(loki_ingester_wal_logged_bytes_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Written to disk for WAL records"
      },
      {
       "expr": "sum(rate(loki_ingester_wal_discarded_bytes_total{job=\"$jobs\"}[$__rate_interval])) by (reason)",
       "legendFormat": "WAL segment bytes discarded during replay / {{ reason }}"
      },
      {
       "expr": "sum(rate(loki_ingester_wal_discarded_bytes_total{job=\"$jobs\"}[$__rate_interval])) by (reason)",
       "legendFormat": "Recovered from the WAL"
      }
     ]
    },
    {
     "title": "Loki Ingester - WAL Recovery Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 238 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(loki_ingester_wal_recovered_entries_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Entries recovered from the WAL"
      },
      {
       "expr": "rate(loki_ingester_wal_recovered_chunks_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Chunks recovered from the WAL checkpoints"
      },
      {
       "expr": "rate(loki_ingester_wal_recovered_streams_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Streams recovered from the WAL"
      }
     ]
    },
    {
     "title": "Loki Ingester - WAL Replay Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 238 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "loki_ingester_wal_replay_active{job=\"$jobs\"}",
       "legendFormat": "WAL is replaying"
      },
      {
       "expr": "loki_ingester_wal_replay_flushing{job=\"$jobs\"}",
       "legendFormat": "WAL replay in flushing phase due to backpressure"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki Line Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki - Internal Log Messages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_internal_log_messages_total{job=\"$jobs\"}[$__rate_interval])) by (level)",
       "legendFormat": "{{ protocol }}"
      }
     ]
    },
    {
     "title": "Loki Line - Log Flushes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_log_flushes_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "Log flushes - line-buffered logger"
      }
     ]
    },
    {
     "title": "Loki Line - Line Size Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
     "targets": [
      {
       "expr": "rate(loki_bytes_per_line_bucket{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Loki Line - Line Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_bytes_per_line_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "Number of bytes per line"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki LogQL Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki LogQL - Lines Received From Ingester",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(loki_logql_querystats_ingester_sent_lines_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Lines"
      }
     ]
    },
    {
     "title": "Loki LogQL - Duplicates Found",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(loki_logql_querystats_duplicates_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Lines"
      }
     ]
    },
    {
     "title": "Loki LogQL - Query Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(logql_query_duration_seconds_bucket{job=\"$jobs\"}[$__rate_interval])) by (le,query_type))",
       "legendFormat": "{{ query_type }}"
      }
     ]
    },
    {
     "title": "Loki LogQL - Query Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket{job=\"$jobs\"}[$__rate_interval])) by (le,type,status_code))",
       "legendFormat": "{{ type }} / {{ status_code }}"
      }
     ]
    },
    {
     "title": "Loki LogQL - Query Volume Processed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_bytes_processed_per_seconds_bucket{job=\"$jobs\"}[$__rate_interval])) by (le,type,status_code))",
       "legendFormat": "{{ type }} / {{ status_code }}"
      }
     ]
    },
    {
     "title": "Loki LogQL - Downloaded Chunks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_logql_querystats_downloaded_chunk_total{job=\"$jobs\"}[$__rate_interval])) by(type,status_code)",
       "legendFormat": "{{ type }} / {{ status_code }}"
      }
     ]
    },
    {
     "title": "Loki LogQL - Chunk Download Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_chunk_download_latency_seconds_bucket{job=\"$jobs\"}[$__rate_interval])) by (le,type,status_code))",
       "legendFormat": "{{ type }} / {{ status_code }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki Querier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki Querier - Frontend Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_querier_query_frontend_request_duration_seconds_bucket{job=\"$jobs\"}[$__rate_interval])) by (le,operation,status_code))",
       "legendFormat": "{{ operation }} / {{ status_code }}"
      }
     ]
    },
    {
     "title": "Loki Querier - Frontend Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(loki_query_frontend_log_result_cache_hit_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Cache hits for the frontend cache"
      },
      {
       "expr": "rate(loki_query_frontend_log_result_cache_miss_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Cache misses for the frontend cache"
      }
     ]
    },
    {
     "title": "Loki Querier - Frontend Partitions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_query_frontend_partitions_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "Time-based partitions (sub-requests) per request"
      }
     ]
    },
    {
     "title": "Loki Querier - Frontend Shard Factor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_query_frontend_shard_factor_bucket{job=\"$jobs\"}[$__rate_interval])) by (le,mapper))",
       "legendFormat": "Downstream queries per request / {{ mapper }}"
      }
     ]
    },
    {
     "title": "Loki Querier - Frontend Shards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(loki_query_frontend_sharding_parsed_queries_total{job=\"$jobs\"}[$__rate_interval])) by (le,mapper,type)",
       "legendFormat": "Parsed queries by evaluation type / {{ mapper }} / {{ type }}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_query_frontend_shards_total{job=\"$jobs\"}[$__rate_interval])) by (le,mapper,type))",
       "legendFormat": "Downstream queries by expression type / {{ mapper }} / {{ type }}"
      }
     ]
    },
    {
     "title": "Loki Querier - Index Cache Clients / Workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "loki_querier_query_frontend_clients{job=\"$jobs\"}",
       "legendFormat": "Clients connected to query-frontend"
      },
      {
       "expr": "loki_querier_tail_active{job=\"$jobs\"}",
       "legendFormat": "Active tailers"
      },
      {
       "expr": "loki_querier_tail_active_streams{job=\"$jobs\"}",
       "legendFormat": "Active streams being tailed"
      },
      {
       "expr": "loki_querier_worker_concurrency{job=\"$jobs\"}",
       "legendFormat": "Concurrent querier workers"
      },
      {
       "expr": "loki_querier_worker_inflight_queries{job=\"$jobs\"}",
       "legendFormat": "Queries being processed by the querier workers"
      }
     ]
    },
    {
     "title": "Loki Querier - Index Cache Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(loki_querier_index_cache_gets_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Gets for the index cache"
      },
      {
       "expr": "rate(loki_querier_index_cache_puts_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Puts for the index cache"
      },
      {
       "expr": "rate(loki_querier_index_cache_hits_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Cache hits for the index cache"
      },
      {
       "expr": "rate(loki_querier_index_cache_corruptions_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Cache corruptions for the index cache"
      },
      {
       "expr": "rate(loki_querier_index_cache_encode_errors_total{job=\"$jobs\",instance=\"$host:$instance\"}[$__rate_interval])",
       "legendFormat": "Errors for the index cache while encoding the body"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki Ring Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki Ring - Heathbeats",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(ring_member_heartbeats_total{job=\"$jobs\"}[$__rate_interval])) by (name)",
       "legendFormat": "Heartbeats sent / {{ name }}"
      }
     ]
    },
    {
     "title": "Loki Ring - Tokens",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(ring_member_tokens_owned{job=\"$jobs\"}) by (name)",
       "legendFormat": "Tokens owned / {{ name }}"
      },
      {
       "expr": "sum(ring_member_tokens_to_own{job=\"$jobs\"}) by (name)",
       "legendFormat": "Tokens to be owned / {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki Store Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Loki Store - Fetched / Stored Chunks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum(rate(loki_chunk_store_fetched_chunks_total{job=\"$jobs\"}[$__rate_interval])) by (user)",
       "legendFormat": "Fetched / {{ user }}"
      },
      {
       "expr": "sum(rate(loki_chunk_store_stored_chunks_total{job=\"$jobs\"}[$__rate_interval])) by (user)",
       "legendFormat": "Stored / {{ user }}"
      }
     ]
    },
    {
     "title": "Loki Store - Fetched / Stored Chunk Volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(loki_chunk_store_fetched_chunk_bytes_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Fetched / {{ user }}"
      },
      {
       "expr": "rate(loki_chunk_store_stored_chunk_bytes_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Stored / {{ user }}"
      }
     ]
    },
    {
     "title": "Loki Store - Chunks Per Query Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
     "targets": [
      {
       "expr": "rate(loki_chunk_store_chunks_per_query_bucket{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Loki Store - Chunks Per Query",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_chunk_store_chunks_per_query_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Loki Store - Index Entries Per Chunk Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
     "targets": [
      {
       "expr": "rate(loki_chunk_store_index_entries_per_chunk_bucket{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Loki Store - Index Entries Per Chunk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_chunk_store_index_entries_per_chunk_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Loki Store - Index Lookups Per Query Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
     "targets": [
      {
       "expr": "rate(loki_chunk_store_index_lookups_per_query_bucket{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Loki Store - Index Lookups Per Query",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_chunk_store_index_lookups_per_query_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Loki Store - Series (Pre Intersection) Per Chunk Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
     "targets": [
      {
       "expr": "rate(loki_chunk_store_series_pre_intersection_per_query_bucket{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Loki Store - Series (Pre Intersection) Per Chunk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_chunk_store_series_pre_intersection_per_query_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Loki Store - Series (Post Intersection) Per Chunk Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
     "targets": [
      {
       "expr": "rate(loki_chunk_store_series_post_intersection_per_query_bucket{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Loki Store - Series (Post Intersection) Per Chunk",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_chunk_store_series_post_intersection_per_query_bucket{job=\"$jobs\"}[$__rate_interval])) by (le))",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distributor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Received Lines / sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (tenant) (rate(loki_distributor_lines_received_total[$__rate_interval]))",
       "legendFormat": "distributor / {{ tenant}}"
      }
     ]
    },
    {
     "title": "batch appends sent to ingesters / sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(loki_distributor_ingester_appends_total[$__rate_interval])",
       "legendFormat": "successed"
      },
      {
       "expr": "loki_distributor_ingester_append_failures_total",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "Distributor  Received bytes / sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_bytes_received_total[$__rate_interval])) by (tenant)",
       "legendFormat": "distributor / {{tenant}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go General Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go - Goroutines / Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "go_goroutines{job=\"$jobs\"}",
       "legendFormat": "Goroutines"
      },
      {
       "expr": "go_threads{job=\"$jobs\"}",
       "legendFormat": "Threads"
      }
     ]
    },
    {
     "title": "Go - Goroutines Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(go_sched_latencies_seconds_sum{job=\"$jobs\"}[$__rate_interval])/rate(go_sched_latencies_seconds_count{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Average Goroutine latency"
      }
     ]
    },
    {
     "title": "Go - Goroutines Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
     "targets": [
      {
       "expr": "rate(go_sched_latencies_seconds_bucket{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Memory Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go - Memory Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memory_classes_heap_free_bytes{job=\"$jobs\"}",
       "legendFormat": "Free memory"
      },
      {
       "expr": "go_memory_classes_heap_objects_bytes{job=\"$jobs\"}",
       "legendFormat": "Allocated objects memory"
      },
      {
       "expr": "go_memory_classes_heap_released_bytes{job=\"$jobs\"}",
       "legendFormat": "Released memory"
      },
      {
       "expr": "go_memory_classes_heap_stacks_bytes{job=\"$jobs\"}",
       "legendFormat": "Stack reserved memory"
      },
      {
       "expr": "go_memory_classes_heap_unused_bytes{job=\"$jobs\"}",
       "legendFormat": "Reserved unused memory"
      }
     ]
    },
    {
     "title": "Go - Memory Metadata",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memory_classes_metadata_mcache_free_bytes{job=\"$jobs\"}",
       "legendFormat": "Free mcache memory"
      },
      {
       "expr": "go_memory_classes_metadata_mcache_inuse_bytes{job=\"$jobs\"}",
       "legendFormat": "Used mcache memory"
      },
      {
       "expr": "go_memory_classes_metadata_mspan_free_bytes{job=\"$jobs\"}",
       "legendFormat": "Free mspan memory"
      },
      {
       "expr": "go_memory_classes_metadata_mspan_inuse_bytes{job=\"$jobs\"}",
       "legendFormat": "Used mspan memory"
      },
      {
       "expr": "go_memory_classes_metadata_other_bytes{job=\"$jobs\"}",
       "legendFormat": "Used other metadata memory"
      },
      {
       "expr": "go_memory_classes_other_bytes{job=\"$jobs\"}",
       "legendFormat": "Used other memory"
      },
      {
       "expr": "go_memory_classes_profiling_buckets_bytes{job=\"$jobs\"}",
       "legendFormat": "Used profiling bucket memory"
      }
     ]
    },
    {
     "title": "Go - Heap Object Allocation / Free Sizes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(go_gc_heap_allocs_bytes_total{job=\"$jobs\"}[$__rate_interval])/rate(go_gc_heap_allocs_objects_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Average object size allocated to the heap by the application"
      },
      {
       "expr": "rate(go_gc_heap_frees_bytes_total{job=\"$jobs\"}[$__rate_interval])/rate(go_gc_heap_frees_objects_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Average object size freed from the heap by the GC"
      }
     ]
    },
    {
     "title": "Go - Heap Free Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 173 },
     "targets": [
      {
       "expr": "rate(go_gc_heap_frees_by_size_bytes_bucket{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Go - Heap Allocation Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
     "targets": [
      {
       "expr": "rate(go_gc_heap_allocs_by_size_bytes_bucket{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go GC Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go - Garbage Collection Cycles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 207 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "rate(go_gc_cycles_total_gc_cycles_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Count of all completed GC cycles"
      },
      {
       "expr": "rate(go_gc_cycles_automatic_gc_cycles_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Count of completed GC cycles generated by the Go runtime"
      },
      {
       "expr": "rate(go_gc_cycles_forced_gc_cycles_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Count of completed GC cycles forced by the application."
      }
     ]
    },
    {
     "title": "Go - Garbage Collection Pause Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 207 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_sum{job=\"$jobs\"}[$__rate_interval])/rate(go_gc_duration_seconds_count{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Average GC cycle pause duration"
      },
      {
       "expr": "rate(go_gc_pauses_seconds_sum{job=\"$jobs\"}[$__rate_interval])/rate(go_gc_pauses_seconds_count{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Average GC cycle halt duration"
      }
     ]
    },
    {
     "title": "Go - Garbage Collection Pauses Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 215 },
     "targets": [
      {
       "expr": "rate(go_gc_pauses_seconds_bucket{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - CPU seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"$jobs\"}[$__rate_interval])",
       "legendFormat": "Total user and system CPU time spent in seconds"
      }
     ]
    },
    {
     "title": "Process - Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_virtual_memory_bytes{job=\"$jobs\"}",
       "legendFormat": "Virtual memory size"
      },
      {
       "expr": "process_resident_memory_bytes{job=\"$jobs\"}",
       "legendFormat": "Resident memory size"
      }
     ]
    },
    {
     "title": "Process - File descriptors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 232 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "process_max_fds{job=\"$jobs\"}",
       "legendFormat": "Maximum number of open file descriptors"
      },
      {
       "expr": "process_open_fds{job=\"$jobs\"}",
       "legendFormat": "Number of open file descriptors"
      }
     ]
    }
   ]
  }
 ]
}