{
 "title": "System Metrics",
 "tags": [ "telegraf" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(disk_used_percent{job=\"$job\"},host)"
    }
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": {
     "query": "label_values(disk_used_percent{job=\"$job\", host=\"$host\"},device)"
    }
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(net_bytes_sent{job=\"$job\", host=\"$host\"},interface)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,2m,5m,10m,15m" }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPUs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "system_n_cpus{job=\"$job\", host=\"$host\"}"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "processes_total{job=\"$job\", host=\"$host\"}"
      }
     ]
    },
    {
     "title": "Network Byets Recevied/Send per sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(net_bytes_recv{job=\"$job\", host=\"$host\", interface=\"$interface\"}[$interval])",
       "legendFormat": "{{interface}} - Recieved"
      },
      {
       "expr": "rate(net_bytes_sent{job=\"$job\", host=\"$host\", interface=\"$interface\"}[$interval])",
       "legendFormat": "{{interface}} - Send"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mem_total{job=\"$job\", host=\"$host\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "system_uptime{job=\"$job\", host=\"$host\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Used",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(100-cpu_usage_idle{job=\"$job\", host=\"$host\", cpu=\"cpu-total\"})"
      }
     ]
    },
    {
     "title": "CPU Total %",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cpu_usage_user{job=\"$job\", host=\"$host\", cpu=\"cpu-total\"}",
       "legendFormat": "User"
      },
      {
       "expr": "cpu_usage_system{job=\"$job\", host=\"$host\", cpu=\"cpu-total\"}",
       "legendFormat": "System"
      },
      {
       "expr": "cpu_usage_idle{job=\"$job\", host=\"$host\", cpu=\"cpu-total\"}",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_load1{job=\"$job\", host=\"$host\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "system_load5{job=\"$job\", host=\"$host\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "system_load15{job=\"$job\", host=\"$host\"}",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "processes_blocked{job=\"$job\", host=\"$host\"}",
       "legendFormat": "Blocked"
      },
      {
       "expr": "processes_dead{job=\"$job\", host=\"$host\"}",
       "legendFormat": "Dead"
      },
      {
       "expr": "processes_idle{job=\"$job\", host=\"$host\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "processes_paging{job=\"$job\", host=\"$host\"}",
       "legendFormat": "Paging"
      },
      {
       "expr": "processes_running{job=\"$job\", host=\"$host\"}",
       "legendFormat": "Running"
      },
      {
       "expr": "processes_sleeping{job=\"$job\", host=\"$host\"}",
       "legendFormat": "Sleeping"
      },
      {
       "expr": "processes_stopped{job=\"$job\", host=\"$host\"}",
       "legendFormat": "Stopped"
      },
      {
       "expr": "processes_unknown{job=\"$job\", host=\"$host\"}",
       "legendFormat": "Unknown"
      },
      {
       "expr": "processes_zombies{job=\"$job\", host=\"$host\"}",
       "legendFormat": "Zombies"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mem_used_percent{job=\"$job\", host=\"$host\"}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 20, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mem_used{job=\"$job\", host=\"$host\"}",
       "legendFormat": "mem_used"
      },
      {
       "expr": "mem_buffered{job=\"$job\", host=\"$host\"}",
       "legendFormat": "mem_buffered"
      },
      {
       "expr": "mem_cached{job=\"$job\", host=\"$host\"}",
       "legendFormat": "mem_cached"
      },
      {
       "expr": "swap_used{job=\"$job\", host=\"$host\"}",
       "legendFormat": "mem_swap"
      },
      {
       "expr": "mem_free{job=\"$job\", host=\"$host\"}",
       "legendFormat": "mem_free"
      }
     ]
    }
   ]
  },
  {
   "title": "Block devices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disks Usages",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "disk_used_percent{job=\"$job\", host=\"$host\", device=\"$disk\"}",
       "legendFormat": "{{device}} - \"{{path}}\""
      }
     ]
    },
    {
     "title": "Disk IO Reads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(diskio_read_bytes{job=\"$job\", host=\"$host\", name!~\"dm-[0-9]\", name!~'loop.+'}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk IO Write",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(diskio_write_bytes{job=\"$job\", host=\"$host\", name!~\"dm-[0-9]\", name!~'loop.+'}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk IO Util",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(diskio_io_time{job=\"$job\", host=\"$host\", name!~'loop.+'}[$interval])/10",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Docker Overall Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Running",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "docker_n_containers_running{host=\"$host\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Containers Stopped",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "docker_n_containers_stopped{host=\"$host\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU (Container)",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by(container_name) (docker_container_cpu_usage_percent{host=\"$host\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory (Container)",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by(container_name) (docker_container_mem_usage_percent{host=\"$host\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Docker Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Info",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "avg by(container_image, container_status, container_version, container_name) (docker_container_status_uptime_ns{host=\"$host\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Throttling Rate (ns/s)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ns/s" } },
     "targets": [
      {
       "expr": "avg by(container_name) (rate(docker_container_cpu_throttling_throttled_time{host=\"$host\"}[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processes Memory Consumed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(container_name) (docker_container_mem_active_anon{host=\"$host\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Write Bytes / sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg by(container_name) (rate(docker_container_blkio_io_service_bytes_recursive_write{host=\"$host\"}[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Read Bytes / sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg by(container_name) (rate(docker_container_blkio_io_service_bytes_recursive_read{host=\"$host\"}[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Bytes Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg by(container_name) (rate(docker_container_net_rx_bytes{host=\"$host\"}[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network Bytes Sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "avg by(container_name) (rate(docker_container_net_tx_bytes{host=\"$host\"}[$interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}