version: '3.8'

services:
  telegraf:
    image: telegraf:1.28-alpine
    container_name: telegraf
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /$DOCKER_SOCKET:$DOCKER_SOCKET
      - /proc:/rootfs/proc:ro
      - /sys:/rootfs/sys:ro
      - /etc:/rootfs/etc:ro
    environment:
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    ports:
      - "${PROMETHEUS_PORT}:9273"
    user: "telegraf:$PRIVILEGED_USER_ID"
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:9273/metrics || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
