version: '3.8'

volumes:
  victorialogs-data:

services:
  victorialogs:
    image: victoriametrics/victoria-logs:${VICTORIALOGS_VERSION}
    container_name: victorialogs
    ports:
      - "${VICTORIALOGS_PORT}:9428"
    volumes:
      - ${VICTORIALOGS_DATA_DIR:-victorialogs-data}:/victoria-logs-data
    command:
      - "--storageDataPath=/victoria-logs-data"
      - "--retentionPeriod=${VICTORIALOGS_RETENTION_PERIOD}"
      - "--retention.maxDiskSpaceUsageBytes=${VICTORIALOGS_MAX_DISK_SIZE}"
      - "--loggerLevel=${VICTORIALOGS_LOG_LEVEL}"
      - "--httpListenAddr=:9428"
      - "--memory.allowedBytes=${VICTORIALOGS_MEMORY_ALLOWED_BYTES}"
      - "--search.maxConcurrentRequests=${VICTORIALOGS_MAX_CONCURRENT_REQUESTS}"
    environment:
      - GOMAXPROCS=${VICTORIALOGS_GO_MAX_PROCS}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - victorialogs
      - monitoring-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:9428/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  victorialogs:
    driver: bridge
  monitoring-network:
    external: true